version: "3.8"
services:
  database:
    container_name: notes_postgres
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data/

volumes:
  db-data: