spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notes_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    cache-names: notes
    caffeine:
      spec: maximumSize=100, expireAfterWrite=5m

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml

  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev

  liquibase:
    contexts: dev

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: ${TEST_CONTAINER_DB_URL}
    username: ${TEST_CONTAINER_DB_USERNAME}
    password: ${TEST_CONTAINER_DB_PASSWORD}

  jpa:
    show-sql: false

  liquibase:
    contexts: test
    drop-first: true
