name: Continuous Integration

on:
  push:
    branches: [ '*', '!main' ]

  workflow_dispatch:

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew clean build
