name: Continuous Integration

on:
  push:
    branches: [ '*', '!main'  ]

  workflow_dispatch:

env:
#  POSTGRESQL_VERSION: 13.1
#  POSTGRESQL_DB: notes_db
#  POSTGRESQL_USER: postgres
#  POSTGRESQL_PASSWORD: password
  JAVA_VERSION: 15
  JAVA_DISTRIBUTION: 'adopt'

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

#    services:
#      postgres:
#        image: postgres:13-alpine
#        env:
#          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
#          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
#          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew clean build
